### ISSUE TITLE
In Test "testNilObjectCannotBeConvertedToString", can't find docs on what should be returned...

### ISSUE THREAD

**Issue by kcorey** [sl4m/gnu_smalltalk_koans#10]
Rank Smalltalk beginner here, stepping through the test cases. I came across the test testNilObjectCannotBeConvertedToString, in file src/koans/TestObject.st.

How frustrating!

I have no idea what kind of Exception to put in here.  I've tried a generic "Exception", but that doesn't work.  I've tried googling for 'toRaise', about 'Exception' class, but still no luck.

Then I tried loading the repl:
```
GNU Smalltalk ready
st> [ nil asString ]
a BlockClosure

```

But nope...it's not a BlockClosure, or UndefinedObject.

Obviously the actual value is "not revealed", so I can't see what it should be.

Any suggestions on how to move forward here?

**Comment by kcorey** [comment]
Drat!  It's always the way.  Post a public comment, and then almost immediately find the answer.

At the REPL, I typed 'nil asString.' without the brackets, and that gave me the answer.

**Comment by sl4m** [comment]
@kcorey Happens to me all the time. :) The block was needed in the `expect:toRaise` message to make it easier to control and capture the exception being raised inside the block. Sorry if that was confusing. I'm glad you sorted out the answer. 👍
