### ISSUE TITLE
Font colour in the koans web page makes the text unreadable

### ISSUE THREAD

**Issue by js-ojus** [sl4m/gnu_smalltalk_koans#9]
The light grey text on white background makes it so extremely difficult to read that I have given up trying to read it.  Please consider making the text darker.

**Comment by sl4m** [comment]
@js-ojus Hi, thanks for checking out the koans. Are you speaking in regards to the website, https://skim.la/gnu_smalltalk_koans ?

**Comment by js-ojus** [comment]
Yes @sl4m, I refer to that web site.  Thanks!

**Comment by sl4m** [comment]
@js-ojus I agree, it's not that easy to read and haven't thought about visual impairment, sorry about that. I'm happy to accept a PR on the `gh-pages` branch to a visual that you think is more suitable for you and the rest of the audience.

**Comment by sl4m** [comment]
This should be sorted now.
